options:
  application-config:
    type: string
    description: >
      Spring Boot configuration properties in JSON format, it will be passed to 
      the SPRING_APPLICATION_JSON environment variable.
    default: ""
